-- 코드를 입력하세요
SELECT BOK.AUTHOR_ID, AUT.AUTHOR_NAME, BOK.CATEGORY, SUM(BOK.PRICE * BKS.SALES) AS "TOTAL_SALES"
FROM BOOK BOK
   , AUTHOR AUT
   , BOOK_SALES BKS
WHERE TO_CHAR(BKS.SALES_DATE, 'YYYY-MM-DD') BETWEEN '2022-01-01' AND '2022-01-31'
  AND BOK.BOOK_ID = BKS.BOOK_ID
  AND BOK.AUTHOR_ID = AUT.AUTHOR_ID
GROUP BY BOK.AUTHOR_ID, AUT.AUTHOR_NAME, BOK.CATEGORY
ORDER BY BOK.AUTHOR_ID ASC, BOK.CATEGORY DESC


-- , BOK.PRICE, BKS.SALES

-- , (BOK.PRICE * BKS.SALES) AS "TOTAL_SALES"