-- 코드를 입력하세요
SELECT PROD.PRODUCT_CODE AS "PRODUCT_CODE", SUM((PROD.PRICE * SALE.SALES_AMOUNT)) AS "SALES"
FROM PRODUCT PROD
    ,OFFLINE_SALE SALE
WHERE PROD.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY 2 DESC, 1 ASC