-- 코드를 입력하세요
SELECT RN.ANIMAL_ID, RN.NAME
FROM (
        SELECT INS.ANIMAL_ID, INS.NAME, AUT.DATETIME - INS.DATETIME
        FROM ANIMAL_INS INS
           , ANIMAL_OUTS AUT
        WHERE INS.ANIMAL_ID = AUT.ANIMAL_ID
        ORDER BY (AUT.DATETIME - INS.DATETIME) DESC ) RN
WHERE ROWNUM <= 2