-- 코드를 입력하세요
SELECT USR.USER_ID, USR.NICKNAME, (USR.CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2) AS "전체주소", (SUBSTR(USR.TLNO, 1, 3) || '-' || SUBSTR(USR.TLNO, 4, 4) || '-' || SUBSTR(USR.TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_BOARD BRD
    ,USED_GOODS_USER USR
WHERE BRD.WRITER_ID = USR.USER_ID
GROUP BY USR.USER_ID, USR.NICKNAME, (USR.CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2), USR.TLNO
HAVING COUNT(BRD.WRITER_ID) >= 3
ORDER BY user_id DESC