-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
    , ANIMAL_OUTS AUT
WHERE INS.SEX_UPON_INTAKE LIKE '%Intact%'
      AND (AUT.SEX_UPON_OUTCOME LIKE '%Spayed%' OR AUT.SEX_UPON_OUTCOME LIKE '%Neutered%')
      AND INS.ANIMAL_ID = AUT.ANIMAL_ID
ORDER BY 1