SELECT PRD.PRODUCT_ID, PRD.PRODUCT_NAME, SUM((PRD.PRICE * ORD.AMOUNT))
FROM FOOD_PRODUCT PRD, FOOD_ORDER ORD
WHERE TO_CHAR(ORD.PRODUCE_DATE, 'YYYY-MM-DD') BETWEEN '2022-05-01' AND '2022-05-31' 
  AND ORD.PRODUCT_ID = PRD.PRODUCT_ID
  
GROUP BY PRD.PRODUCT_ID, PRD.PRODUCT_NAME

ORDER BY 3 DESC, 1 ASC