-- 코드를 입력하세요
SELECT APP.APNT_NO, PAT.PT_NAME, PAT.PT_NO, APP.MCDP_CD, DOC.DR_NAME, APP.APNT_YMD
FROM PATIENT PAT
  ,  DOCTOR DOC
  ,  APPOINTMENT APP
WHERE TO_CHAR(APP.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
  AND PAT.PT_NO = APP.PT_NO
  AND DOC.DR_ID = APP.MDDR_ID
  AND APP.MCDP_CD = 'CS'
  AND APP.APNT_CNCL_YN = 'N'
ORDER BY APP.APNT_YMD ASC;