-- 코드를 입력하세요
SELECT USR.USER_ID, USR.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM  USED_GOODS_BOARD BRD
    , USED_GOODS_USER USR
WHERE BRD.STATUS = 'DONE'  
  AND BRD.WRITER_ID = USR.USER_ID
GROUP BY USR.USER_ID, USR.NICKNAME
HAVING SUM(PRICE) >= '700000'
ORDER BY SUM(PRICE)