-- 코드를 입력하세요
SELECT DECODE(TO_CHAR(DATETIME, 'HH24'), '09', '9', TO_CHAR(DATETIME, 'HH24')) AS "HOUR", COUNT(*) AS "COUNT"
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24') ASC