-- 코드를 입력하세요
SELECT DISTINCT(CAR.CAR_ID)
FROM  CAR_RENTAL_COMPANY_CAR CAR
    , CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
WHERE TO_CHAR(HIS.START_DATE, 'YYYY-MM-DD') BETWEEN '2022-10-01' AND '2022-10-31'
  AND CAR.CAR_ID = HIS.CAR_ID
  AND CAR.CAR_TYPE = '세단'
ORDER BY CAR.CAR_ID DESC