-- 코드를 입력하세요
SELECT A.TITLE, B.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
       TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATE_DATE
FROM USED_GOODS_BOARD A,
     USED_GOODS_REPLY B
WHERE A.BOARD_ID(+) = B.BOARD_ID
      AND TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;