



SELECT ('/home/grep/src/' || UGB.BOARD_ID || '/' || UGF.FILE_ID || UGF.FILE_NAME || UGF.FILE_EXT) AS "FILE_PATH"
FROM USED_GOODS_BOARD UGB
   , USED_GOODS_FILE UGF
WHERE UGB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
  AND UGB.BOARD_ID = UGF.BOARD_ID
ORDER BY FILE_ID DESC;
