-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
    ,BOOK_SALES BS
WHERE TO_CHAR(BS.SALES_DATE, 'YYYY-MM-DD') BETWEEN '2022-01-01' AND '2022-01-31'
      AND B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;