SELECT 
    CATEGORY, PRICE AS "MAX_PIRCE", PRODUCT_NAME
    
FROM 
    (SELECT CATEGORY, PRODUCT_NAME, PRICE, ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rn FROM FOOD_PRODUCT WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
    
WHERE 
    rn = 1
    
ORDER BY 
    PRICE DESC