-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') 
FROM AUTHOR A
    , BOOK B
WHERE B.CATEGORY = '경제'
        AND B.AUTHOR_ID = A.AUTHOR_ID

ORDER BY B.PUBLISHED_DATE ASC
